---
- name: Check if the kubernetes python module is usable from ansible
  ansible.builtin.command: "{{ ansible_python_interpreter }} -c 'import kubernetes'"
  changed_when: false

- name: Check if KUBECONFIG is correctly set
  ansible.builtin.debug:
    msg: "KUBECONFIG is not set, falling back to ~/.kube/config"
  when: kubeconfig is not defined or kubeconfig | length == 0

- name: Check if ~/.kube/config exists
  ansible.builtin.stat:
    path: "{{ kubeconfig_backup }}"
  register: kubeconfig_result

- name: Fail if both KUBECONFIG and ~/.kube/config do not exist
  ansible.builtin.fail:
    msg: "{{ kubeconfig_backup }} not found and KUBECONFIG unset. Bailing out."
  failed_when: not kubeconfig_result.stat.exists and (kubeconfig is not defined or kubeconfig | length == 0)
