---
- include_tasks: pre_check.yaml

- name: Create temporary file for our default policy
  ansible.builtin.tempfile:
    state: file
    suffix: policyhcl
  register: temp_password_policy

- name: Template the default policy
  ansible.builtin.template:
    src: templates/default_password_policy.j2
    dest: "{{ temp_password_policy.path }}"
    mode: '0600'

  # This has to be shell because of the use of stdin and pipes
  # It can be dropped once https://github.com/ansible-collections/kubernetes.core/issues/506
  # is implemented
- name: Write default password policy into the vault pod
  ansible.builtin.shell: |
    cat "{{ temp_password_policy.path }}" | oc exec -n "{{ vault_ns }}" "{{ vault_pod }}" -i -- sh -c 'cat - > /tmp/password_policy.hcl'

- name: Configure default password policy
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: vault write sys/policies/password/"{{ vault_password_policy_name }}" policy=@/tmp/password_policy.hcl

  # This has to be shell because of the use of stdin and pipes
  # It can be dropped once https://github.com/ansible-collections/kubernetes.core/issues/506
  # is implemented
- name: Write additional password policies into the vault pod
  ansible.builtin.shell: |
    cat "{{ item.value }}" | oc exec -n "{{ vault_ns }}" "{{ vault_pod }}" -i -- sh -c 'cat - > /tmp/{{ item.key }}.hcl'
  loop:
    "{{ vault_password_policy_extra_policies | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: vault_password_policy_extra_policies | length > 0

- name: Configure additional password policies when defined
  kubernetes.core.k8s_exec:
    namespace: "{{ vault_ns }}"
    pod: "{{ vault_pod }}"
    command: vault write sys/policies/password/"{{ item.key }}" policy=@/tmp/"{{ item.key }}".hcl
  loop:
    "{{ vault_password_policy_extra_policies | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: vault_password_policy_extra_policies | length > 0
